apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: otyoaiodq-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-3f0a0f0f41.s3d8.p3.openshiftapps.com/rhtap/rhtap-qe-python:3d105b6890a4937ce5e897124ceaed1d6a3edf94@sha256:cdafb5ac2947626a3562650554b56ad68d653586fc93f2c87c6bd169c7b8575a
          name: container-image
